### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by TheDivineCodes** [MarsX-dev/floatui#27]
Warning: Invalid DOM property `clip-path`. Did you mean `clipPath`?
    at g
    at svg
    at IconGithub (webpack-internal:///./components/icons/IconGithub.tsx:8:23)
    at a
    at div
    at nav
    at header
    at __WEBPACK_DEFAULT_EXPORT__
    at main
    at Home
    at AppProvider (webpack-internal:///./context/contextApp.tsx:19:13)
    at App (webpack-internal:///./pages/_app.tsx:16:16)
    at StyleRegistry (F:\React\floatui-main_3\floatui-main\node_modules\.pnpm\styled-jsx@5.1.1_react@18.2.0\node_modules\styled-jsx\dist\index\index.js:449:36)
    at PathnameContextProviderAdapter (F:\React\floatui-main_3\floatui-main\node_modules\.pnpm\next@13.1.6_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\shared\lib\router\adapters.js:60:11)
    at AppContainer (F:\React\floatui-main_3\floatui-main\node_modules\.pnpm\next@13.1.6_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\render.js:290:29)
    at AppContainerWithIsomorphicFiberStructure (F:\React\floatui-main_3\floatui-main\node_modules\.pnpm\next@13.1.6_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\render.js:326:57)
    at div
    at Body (F:\React\floatui-main_3\floatui-main\node_modules\.pnpm\next@13.1.6_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\render.js:613:21)
Warning: Invalid DOM property `fill-rule`. Did you mean `fillRule`?
    at path
    at g
    at svg
    at IconGithub (webpack-internal:///./components/icons/IconGithub.tsx:8:23)
    at a
    at div
    at nav
    at header
    at __WEBPACK_DEFAULT_EXPORT__
    at main
    at Home
    at AppProvider (webpack-internal:///./context/contextApp.tsx:19:13)
    at App (webpack-internal:///./pages/_app.tsx:16:16)
    at StyleRegistry (F:\React\floatui-main_3\floatui-main\node_modules\.pnpm\styled-jsx@5.1.1_react@18.2.0\node_modules\styled-jsx\dist\index\index.js:449:36)
    at PathnameContextProviderAdapter (F:\React\floatui-main_3\floatui-main\node_modules\.pnpm\next@13.1.6_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\shared\lib\router\adapters.js:60:11)
    at AppContainer (F:\React\floatui-main_3\floatui-main\node_modules\.pnpm\next@13.1.6_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\render.js:290:29)
    at AppContainerWithIsomorphicFiberStructure (F:\React\floatui-main_3\floatui-main\node_modules\.pnpm\next@13.1.6_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\render.js:326:57)
    at div
    at Body (F:\React\floatui-main_3\floatui-main\node_modules\.pnpm\next@13.1.6_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\render.js:613:21)
Warning: Invalid DOM property `clip-rule`. Did you mean `clipRule`?
    at path
    at g
    at svg
    at IconGithub (webpack-internal:///./components/icons/IconGithub.tsx:8:23)
    at a
    at div
    at nav
    at header
    at __WEBPACK_DEFAULT_EXPORT__
    at main
    at Home
    at AppProvider (webpack-internal:///./context/contextApp.tsx:19:13)
    at App (webpack-internal:///./pages/_app.tsx:16:16)
    at StyleRegistry (F:\React\floatui-main_3\floatui-main\node_modules\.pnpm\styled-jsx@5.1.1_react@18.2.0\node_modules\styled-jsx\dist\index\index.js:449:36)
    at PathnameContextProviderAdapter (F:\React\floatui-main_3\floatui-main\node_modules\.pnpm\next@13.1.6_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\shared\lib\router\adapters.js:60:11)
    at AppContainer (F:\React\floatui-main_3\floatui-main\node_modules\.pnpm\next@13.1.6_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\render.js:290:29)
    at AppContainerWithIsomorphicFiberStructure (F:\React\floatui-main_3\floatui-main\node_modules\.pnpm\next@13.1.6_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\render.js:326:57)
    at div
    at Body (F:\React\floatui-main_3\floatui-main\node_modules\.pnpm\next@13.1.6_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\render.js:613:21)

I am getting this error after building

**Comment by olabisi09** [comment]
It seems you were trying to render an svg element. Can you show explicitly how you rendered it in your component?

**Comment by sidiDev** [comment]
@olabisi09 Hey thanks for reporting, @tristonarmstrong Fixed it, and we just merged his PR #33
